In [27]:
import cv2
import numpy as np

#get the homography
def getH(pxp, pyp, qxp, qyp, rxp, ryp, sxp, syp):
    px = 0
    py = 0
    qx = 0
    qy = 1125
    rx = 1920
    ry = 1125
    sx = 1920
    sy = 0
    t = np.array([[pxp],[pyp],[qxp],[qyp],[rxp],[ryp],[sxp],[syp]])
    P = np.array([[px, py, 1, 0, 0, 0, -px*pxp, -py*pxp],
                  [0, 0, 0, px, py, 1, -px*pyp, -py*pyp],
                  [qx, qy, 1, 0, 0, 0, -qx*qxp, -qy*qxp],
                  [0, 0, 0, qx, qy, 1, -qx*qyp, -qy*qyp],
                  [rx, ry, 1, 0, 0, 0, -rx*rxp, -ry*rxp],
                  [0, 0, 0, rx, ry, 1, -rx*ryp, -ry*ryp],
                  [sx, sy, 1, 0, 0, 0, -sx*sxp, -sy*sxp],
                  [0, 0, 0, sx, sy, 1, -sx*syp, -sy*syp]])
    pInv = np.linalg.inv(P)
    h = pInv.dot(t)
    H = np.array([[h[0, 0], h[1, 0], h[2, 0]], [h[3, 0], h[4, 0], h[5, 0]], [h[6, 0], h[7, 0], 1]])
    return H

H1 = getH(299, 511, 239, 1607, 1686, 1828, 1775, 357)
H2 = getH(341, 695, 333, 2330, 1884, 2003, 1887, 753)
H3 = getH(108, 440, 117, 1369, 1218, 303, 1100, 1864)


[[-4.27586788e-01  1.60745822e-02  1.08000000e+02]
 [-8.58413733e-01  9.20257291e-01  4.40000000e+02]
 [-8.58412232e-04  6.90135232e-05  1.00000000e+00]]
