In [5]:
import cv2
import numpy as np

#get the homography between two images
def getHomography(im1Pts, im2Pts):
    px = im1Pts[0, 1]
    py = im1Pts[0, 0]
    qx = im1Pts[1, 1]
    qy = im1Pts[1, 0]
    rx = im1Pts[2, 1]
    ry = im1Pts[2, 0]
    sx = im1Pts[3, 1]
    sy = im1Pts[3, 0]
    
    pxp = im2Pts[0, 1]
    pyp = im2Pts[0, 0]
    qxp = im2Pts[1, 1]
    qyp = im2Pts[1, 0]
    rxp = im2Pts[2, 1]
    ryp = im2Pts[2, 0]
    sxp = im2Pts[3, 1]
    syp = im2Pts[3, 0]
    
    t = np.array([[pxp],[pyp],[qxp],[qyp],[rxp],[ryp],[sxp],[syp]])
    P = np.array([[px, py, 1, 0, 0, 0, -px*pxp, -py*pxp],
                  [0, 0, 0, px, py, 1, -px*pyp, -py*pyp],
                  [qx, qy, 1, 0, 0, 0, -qx*qxp, -qy*qxp],
                  [0, 0, 0, qx, qy, 1, -qx*qyp, -qy*qyp],
                  [rx, ry, 1, 0, 0, 0, -rx*rxp, -ry*rxp],
                  [0, 0, 0, rx, ry, 1, -rx*ryp, -ry*ryp],
                  [sx, sy, 1, 0, 0, 0, -sx*sxp, -sy*sxp],
                  [0, 0, 0, sx, sy, 1, -sx*syp, -sy*syp]])
    pInv = np.linalg.inv(P)
    h = pInv.dot(t)
    H = np.array([[h[0, 0], h[1, 0], h[2, 0]], [h[3, 0], h[4, 0], h[5, 0]], [h[6, 0], h[7, 0], 1]])
    return H

#get the resulting image by applying the homgraphy
def newImage(srcIm, destIm, corners, H):
    for row in range(srcIm.shape[0]):
        for col in range(srcIm.shape[1]):
            coord = np.matmul(H, [[row], [col], [1]])
            coord /= coord[2, 0]
            destIm[int(coord[0][0])][int(coord[1][0])] = srcIm[row][col]
    return destIm

catCorners = np.array([[0, 0], [0, 1125], [1920, 1125], [1920, 0]])
im1Corners = np.array([[299, 511], [239, 1607], [1686, 1828], [1775, 357]])
im2Corners = np.array([[341, 695], [333, 2330], [1884, 2003], [1887, 753]])
im3Corners = np.array([[108, 440], [117, 1369], [1100, 1864], [1218, 303]])

H1 = getHomography(catCorners, im1Corners)
print(H1)
H2 = getHomography(catCorners, im2Corners)
H3 = getHomography(catCorners, im3Corners)

im1 = cv2.imread('Task1_Images/painting1.jpeg')
im2 = cv2.imread('Task1_Images/painting2.jpeg')
im3 = cv2.imread('Task1_Images/painting3.jpeg')
imCat = cv2.imread('Task1_Images/kittens.jpeg')

im1New = newImage(imCat, im1, im1Corners, H1)
cv2.imwrite('Task1_Results/Image1.jpeg', im1New)
im2New = newImage(imCat, im2, im2Corners, H2)
cv2.imwrite('Task1_Results/Image2.jpeg', im2New)
im3New = newImage(imCat, im3, im3Corners, H3)
cv2.imwrite('Task1_Results/Image3.jpeg', im3New)        

[[ 9.80395596e-01 -1.27729851e-01  5.11000000e+02]
 [-5.24152025e-02  5.32473547e-01  2.99000000e+02]
 [ 3.84155172e-06 -1.33113495e-04  1.00000000e+00]]


True